name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v5

      - name: Build
        run: make

      - name: Upload NRO
        uses: actions/upload-artifact@v5
        with:
          name: screentest101-nro
          path: screentest101.nro
          if-no-files-found: error
